apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vjpuulf5r-nodejs 
  janus-idp.io/tekton: vjpuulf5r-nodejs
  backstage.io/kubernetes-id: vjpuulf5r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vjpuulf5r-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml